// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: customer.proto

package proto

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Created              int64    `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
	LastUpdated          int64    `protobuf:"varint,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}
func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Customer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Customer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Customer) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Customer) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

type GetAllCustomersRequest struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllCustomersRequest) Reset()         { *m = GetAllCustomersRequest{} }
func (m *GetAllCustomersRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllCustomersRequest) ProtoMessage()    {}
func (*GetAllCustomersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}
func (m *GetAllCustomersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCustomersRequest.Unmarshal(m, b)
}
func (m *GetAllCustomersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCustomersRequest.Marshal(b, m, deterministic)
}
func (m *GetAllCustomersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCustomersRequest.Merge(m, src)
}
func (m *GetAllCustomersRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllCustomersRequest.Size(m)
}
func (m *GetAllCustomersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCustomersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCustomersRequest proto.InternalMessageInfo

func (m *GetAllCustomersRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAllCustomersRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetAllCustomersResponse struct {
	Customers            []Customer `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers"`
	Err                  string     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllCustomersResponse) Reset()         { *m = GetAllCustomersResponse{} }
func (m *GetAllCustomersResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllCustomersResponse) ProtoMessage()    {}
func (*GetAllCustomersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{2}
}
func (m *GetAllCustomersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCustomersResponse.Unmarshal(m, b)
}
func (m *GetAllCustomersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCustomersResponse.Marshal(b, m, deterministic)
}
func (m *GetAllCustomersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCustomersResponse.Merge(m, src)
}
func (m *GetAllCustomersResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllCustomersResponse.Size(m)
}
func (m *GetAllCustomersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCustomersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCustomersResponse proto.InternalMessageInfo

func (m *GetAllCustomersResponse) GetCustomers() []Customer {
	if m != nil {
		return m.Customers
	}
	return nil
}

func (m *GetAllCustomersResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetCustomerByIDRequest struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerByIDRequest) Reset()         { *m = GetCustomerByIDRequest{} }
func (m *GetCustomerByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerByIDRequest) ProtoMessage()    {}
func (*GetCustomerByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{3}
}
func (m *GetCustomerByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerByIDRequest.Unmarshal(m, b)
}
func (m *GetCustomerByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerByIDRequest.Merge(m, src)
}
func (m *GetCustomerByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerByIDRequest.Size(m)
}
func (m *GetCustomerByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerByIDRequest proto.InternalMessageInfo

func (m *GetCustomerByIDRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

type GetCustomerByIDResponse struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCustomerByIDResponse) Reset()         { *m = GetCustomerByIDResponse{} }
func (m *GetCustomerByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerByIDResponse) ProtoMessage()    {}
func (*GetCustomerByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{4}
}
func (m *GetCustomerByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerByIDResponse.Unmarshal(m, b)
}
func (m *GetCustomerByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerByIDResponse.Merge(m, src)
}
func (m *GetCustomerByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerByIDResponse.Size(m)
}
func (m *GetCustomerByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerByIDResponse proto.InternalMessageInfo

func (m *GetCustomerByIDResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *GetCustomerByIDResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type RegisterCustomerRequest struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterCustomerRequest) Reset()         { *m = RegisterCustomerRequest{} }
func (m *RegisterCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerRequest) ProtoMessage()    {}
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{5}
}
func (m *RegisterCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerRequest.Unmarshal(m, b)
}
func (m *RegisterCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerRequest.Merge(m, src)
}
func (m *RegisterCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerRequest.Size(m)
}
func (m *RegisterCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerRequest proto.InternalMessageInfo

func (m *RegisterCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type RegisterCustomerResponse struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterCustomerResponse) Reset()         { *m = RegisterCustomerResponse{} }
func (m *RegisterCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerResponse) ProtoMessage()    {}
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{6}
}
func (m *RegisterCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerResponse.Unmarshal(m, b)
}
func (m *RegisterCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerResponse.Merge(m, src)
}
func (m *RegisterCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerResponse.Size(m)
}
func (m *RegisterCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerResponse proto.InternalMessageInfo

func (m *RegisterCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *RegisterCustomerResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UnregisterCustomerRequest struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterCustomerRequest) Reset()         { *m = UnregisterCustomerRequest{} }
func (m *UnregisterCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterCustomerRequest) ProtoMessage()    {}
func (*UnregisterCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{7}
}
func (m *UnregisterCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterCustomerRequest.Unmarshal(m, b)
}
func (m *UnregisterCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterCustomerRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterCustomerRequest.Merge(m, src)
}
func (m *UnregisterCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterCustomerRequest.Size(m)
}
func (m *UnregisterCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterCustomerRequest proto.InternalMessageInfo

func (m *UnregisterCustomerRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

type UnregisterCustomerResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterCustomerResponse) Reset()         { *m = UnregisterCustomerResponse{} }
func (m *UnregisterCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterCustomerResponse) ProtoMessage()    {}
func (*UnregisterCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{8}
}
func (m *UnregisterCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterCustomerResponse.Unmarshal(m, b)
}
func (m *UnregisterCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterCustomerResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterCustomerResponse.Merge(m, src)
}
func (m *UnregisterCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterCustomerResponse.Size(m)
}
func (m *UnregisterCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterCustomerResponse proto.InternalMessageInfo

func (m *UnregisterCustomerResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Customer)(nil), "Customer")
	proto.RegisterType((*GetAllCustomersRequest)(nil), "GetAllCustomersRequest")
	proto.RegisterType((*GetAllCustomersResponse)(nil), "GetAllCustomersResponse")
	proto.RegisterType((*GetCustomerByIDRequest)(nil), "GetCustomerByIDRequest")
	proto.RegisterType((*GetCustomerByIDResponse)(nil), "GetCustomerByIDResponse")
	proto.RegisterType((*RegisterCustomerRequest)(nil), "RegisterCustomerRequest")
	proto.RegisterType((*RegisterCustomerResponse)(nil), "RegisterCustomerResponse")
	proto.RegisterType((*UnregisterCustomerRequest)(nil), "UnregisterCustomerRequest")
	proto.RegisterType((*UnregisterCustomerResponse)(nil), "UnregisterCustomerResponse")
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46) }

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x41, 0x8b, 0xd3, 0x4e,
	0x18, 0xc6, 0xff, 0xd9, 0xb6, 0xdb, 0xe6, 0xed, 0xb2, 0xbb, 0x0c, 0xcb, 0x36, 0xcd, 0xfe, 0xa5,
	0x31, 0x20, 0x94, 0xc5, 0x26, 0xb0, 0x9e, 0x94, 0x45, 0xec, 0x2a, 0x2e, 0x0b, 0x8b, 0x60, 0xca,
	0x5e, 0xf6, 0xb2, 0xc6, 0x76, 0x1a, 0x07, 0xd2, 0x99, 0x98, 0x99, 0xba, 0x8a, 0x78, 0xf1, 0x23,
	0xd4, 0x83, 0x17, 0xcf, 0x7e, 0x01, 0xcf, 0xde, 0x3d, 0x0a, 0xde, 0x3d, 0xf9, 0x41, 0x24, 0x93,
	0x4c, 0x5a, 0xdb, 0x84, 0x0a, 0x9e, 0x3a, 0xf3, 0x3e, 0xcf, 0xcc, 0xfc, 0xde, 0x27, 0xbc, 0x85,
	0xed, 0xe1, 0x94, 0x0b, 0x36, 0xc1, 0xb1, 0x13, 0xc5, 0x4c, 0x30, 0xf3, 0xff, 0x80, 0xb1, 0x20,
	0xc4, 0xae, 0x1f, 0x11, 0xd7, 0xa7, 0x94, 0x09, 0x5f, 0x10, 0x46, 0x79, 0xa6, 0xde, 0x96, 0x3f,
	0xc3, 0x5e, 0x80, 0x69, 0x8f, 0x5f, 0xfb, 0x41, 0x80, 0x63, 0x97, 0x45, 0xd2, 0x51, 0xe0, 0xde,
	0x0b, 0x58, 0xc0, 0xe4, 0xd2, 0x4d, 0x56, 0x69, 0xd5, 0xfe, 0xae, 0x41, 0xe3, 0x61, 0xf6, 0x28,
	0xea, 0x40, 0x53, 0x01, 0x5c, 0x91, 0x91, 0xa1, 0x59, 0x5a, 0xb7, 0xe2, 0x81, 0x2a, 0x9d, 0x8d,
	0xd0, 0x0d, 0x80, 0x31, 0x89, 0xb9, 0xb8, 0xa2, 0xfe, 0x04, 0x1b, 0x1b, 0x96, 0xd6, 0xd5, 0x3d,
	0x5d, 0x56, 0x9e, 0xf8, 0x13, 0x8c, 0x0e, 0x40, 0x0f, 0x7d, 0xa5, 0x56, 0xa4, 0xda, 0x48, 0x0a,
	0x52, 0xdc, 0x83, 0x1a, 0x9e, 0xf8, 0x24, 0x34, 0xaa, 0x52, 0x48, 0x37, 0x49, 0x35, 0x7a, 0xc1,
	0x28, 0x36, 0x6a, 0x69, 0x55, 0x6e, 0x90, 0x01, 0xf5, 0x61, 0x8c, 0x7d, 0x81, 0x47, 0xc6, 0xa6,
	0x84, 0x50, 0x5b, 0x74, 0x13, 0xb6, 0xe4, 0x13, 0xd3, 0x68, 0x24, 0xe5, 0xba, 0x94, 0x9b, 0x49,
	0xed, 0x22, 0x2d, 0xd9, 0x8f, 0x61, 0xff, 0x14, 0x8b, 0x7e, 0x18, 0xaa, 0xbe, 0xb8, 0x87, 0x5f,
	0x4e, 0x31, 0x17, 0xc9, 0x63, 0x21, 0x99, 0x10, 0x21, 0x3b, 0xab, 0x7a, 0xe9, 0x06, 0xed, 0xc3,
	0x26, 0x1b, 0x8f, 0x39, 0x16, 0xb2, 0xa1, 0xaa, 0x97, 0xed, 0xec, 0x4b, 0x68, 0xad, 0xdc, 0xc3,
	0x23, 0x46, 0x39, 0x46, 0x3d, 0xd0, 0x55, 0x2a, 0xdc, 0xd0, 0xac, 0x4a, 0xb7, 0x79, 0xa4, 0x3b,
	0xca, 0x76, 0x52, 0xfd, 0xf6, 0xb3, 0xf3, 0x9f, 0x37, 0x77, 0xa0, 0x5d, 0xa8, 0xe0, 0x38, 0xce,
	0xf2, 0x4a, 0x96, 0xf6, 0x5d, 0xc9, 0x98, 0x9f, 0x78, 0x73, 0xf6, 0x48, 0x31, 0xae, 0xfb, 0x06,
	0xb6, 0x27, 0xb1, 0xfe, 0x3c, 0x9a, 0x61, 0xdd, 0x82, 0x86, 0x32, 0xca, 0x83, 0x8b, 0x54, 0x5e,
	0x2e, 0x15, 0xe0, 0x3c, 0x80, 0x96, 0x87, 0x03, 0xc2, 0x05, 0x8e, 0x73, 0x7f, 0xc6, 0xf3, 0x77,
	0x77, 0xda, 0x03, 0x30, 0x56, 0x6f, 0xf8, 0x57, 0xac, 0x63, 0x68, 0x5f, 0xd0, 0xb8, 0x04, 0x6c,
	0x6d, 0x50, 0x0e, 0x98, 0x45, 0xa7, 0x33, 0xa8, 0xec, 0x35, 0x2d, 0x7f, 0xed, 0xe8, 0x4b, 0x0d,
	0x76, 0x94, 0x6d, 0x80, 0xe3, 0x57, 0x64, 0x88, 0xd1, 0x27, 0x0d, 0x76, 0x97, 0xfb, 0x42, 0x86,
	0x53, 0x12, 0x96, 0xd9, 0x76, 0xca, 0x42, 0xb0, 0x07, 0xb3, 0xfe, 0xf1, 0x3c, 0x07, 0x94, 0xe7,
	0x6d, 0xf9, 0x16, 0xc5, 0xd7, 0x96, 0xf2, 0x9b, 0x65, 0xc2, 0xfb, 0x1f, 0xbf, 0x3e, 0x6c, 0x6c,
	0xdb, 0xba, 0xab, 0xae, 0xb8, 0xa7, 0x1d, 0xa2, 0xaf, 0x1a, 0xa0, 0xd5, 0x1e, 0x91, 0xe9, 0x94,
	0xc6, 0x66, 0x1e, 0x38, 0xe5, 0xa1, 0xd8, 0x74, 0xd6, 0x3f, 0x5f, 0x80, 0xec, 0xcc, 0xad, 0x96,
	0x4f, 0x2d, 0xfc, 0x9a, 0x70, 0x41, 0x68, 0x60, 0x29, 0x83, 0xb9, 0xce, 0x20, 0xa1, 0xdb, 0x87,
	0xad, 0x1c, 0xda, 0x7d, 0xbb, 0xf0, 0xcd, 0xde, 0xa1, 0x8f, 0x1a, 0xec, 0x2c, 0xcd, 0x18, 0x6a,
	0x39, 0xc5, 0xd3, 0x6b, 0x1a, 0x4e, 0xc9, 0x38, 0xda, 0x4f, 0x97, 0xb2, 0x3d, 0x27, 0x5c, 0xac,
	0xc2, 0x70, 0xb3, 0x4c, 0x90, 0x98, 0x5b, 0x08, 0xdc, 0xf9, 0xc8, 0x7e, 0x4e, 0xc9, 0x16, 0xc7,
	0x2c, 0x25, 0x2b, 0x98, 0xd9, 0x94, 0xac, 0x68, 0x22, 0xed, 0x67, 0xb3, 0xfe, 0xfd, 0x05, 0x32,
	0xe3, 0x14, 0x8b, 0xe2, 0x24, 0x4b, 0x95, 0x34, 0x42, 0x54, 0x16, 0xe1, 0x49, 0xfd, 0xb2, 0x26,
	0xff, 0xc9, 0x9f, 0x6f, 0xca, 0x9f, 0x3b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x81, 0x78, 0x5d,
	0xd4, 0x44, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	RegisterCustomer(ctx context.Context, in *RegisterCustomerRequest, opts ...grpc.CallOption) (*RegisterCustomerResponse, error)
	UnregisterCustomer(ctx context.Context, in *UnregisterCustomerRequest, opts ...grpc.CallOption) (*UnregisterCustomerResponse, error)
	GetAllCustomers(ctx context.Context, in *GetAllCustomersRequest, opts ...grpc.CallOption) (*GetAllCustomersResponse, error)
	GetCustomerByID(ctx context.Context, in *GetCustomerByIDRequest, opts ...grpc.CallOption) (*GetCustomerByIDResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) RegisterCustomer(ctx context.Context, in *RegisterCustomerRequest, opts ...grpc.CallOption) (*RegisterCustomerResponse, error) {
	out := new(RegisterCustomerResponse)
	err := c.cc.Invoke(ctx, "/CustomerService/RegisterCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) UnregisterCustomer(ctx context.Context, in *UnregisterCustomerRequest, opts ...grpc.CallOption) (*UnregisterCustomerResponse, error) {
	out := new(UnregisterCustomerResponse)
	err := c.cc.Invoke(ctx, "/CustomerService/UnregisterCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetAllCustomers(ctx context.Context, in *GetAllCustomersRequest, opts ...grpc.CallOption) (*GetAllCustomersResponse, error) {
	out := new(GetAllCustomersResponse)
	err := c.cc.Invoke(ctx, "/CustomerService/GetAllCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomerByID(ctx context.Context, in *GetCustomerByIDRequest, opts ...grpc.CallOption) (*GetCustomerByIDResponse, error) {
	out := new(GetCustomerByIDResponse)
	err := c.cc.Invoke(ctx, "/CustomerService/GetCustomerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	RegisterCustomer(context.Context, *RegisterCustomerRequest) (*RegisterCustomerResponse, error)
	UnregisterCustomer(context.Context, *UnregisterCustomerRequest) (*UnregisterCustomerResponse, error)
	GetAllCustomers(context.Context, *GetAllCustomersRequest) (*GetAllCustomersResponse, error)
	GetCustomerByID(context.Context, *GetCustomerByIDRequest) (*GetCustomerByIDResponse, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) RegisterCustomer(ctx context.Context, req *RegisterCustomerRequest) (*RegisterCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCustomer not implemented")
}
func (*UnimplementedCustomerServiceServer) UnregisterCustomer(ctx context.Context, req *UnregisterCustomerRequest) (*UnregisterCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterCustomer not implemented")
}
func (*UnimplementedCustomerServiceServer) GetAllCustomers(ctx context.Context, req *GetAllCustomersRequest) (*GetAllCustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCustomers not implemented")
}
func (*UnimplementedCustomerServiceServer) GetCustomerByID(ctx context.Context, req *GetCustomerByIDRequest) (*GetCustomerByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerByID not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_RegisterCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).RegisterCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomerService/RegisterCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).RegisterCustomer(ctx, req.(*RegisterCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_UnregisterCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).UnregisterCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomerService/UnregisterCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).UnregisterCustomer(ctx, req.(*UnregisterCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetAllCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetAllCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomerService/GetAllCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetAllCustomers(ctx, req.(*GetAllCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomerService/GetCustomerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomerByID(ctx, req.(*GetCustomerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCustomer",
			Handler:    _CustomerService_RegisterCustomer_Handler,
		},
		{
			MethodName: "UnregisterCustomer",
			Handler:    _CustomerService_UnregisterCustomer_Handler,
		},
		{
			MethodName: "GetAllCustomers",
			Handler:    _CustomerService_GetAllCustomers_Handler,
		},
		{
			MethodName: "GetCustomerByID",
			Handler:    _CustomerService_GetCustomerByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
