// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reservation.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Reservation struct {
	ReservationId        int64    `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	SeatCount            int64    `protobuf:"varint,2,opt,name=seat_count,json=seatCount,proto3" json:"seat_count,omitempty"`
	StartTime            string   `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ReservationName      string   `protobuf:"bytes,4,opt,name=reservation_name,json=reservationName,proto3" json:"reservation_name,omitempty"`
	CustomerId           int64    `protobuf:"varint,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Comments             string   `protobuf:"bytes,7,opt,name=comments,proto3" json:"comments,omitempty"`
	Created              int64    `protobuf:"varint,8,opt,name=created,proto3" json:"created,omitempty"`
	LastUpdated          int64    `protobuf:"varint,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reservation) Reset()         { *m = Reservation{} }
func (m *Reservation) String() string { return proto.CompactTextString(m) }
func (*Reservation) ProtoMessage()    {}
func (*Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{0}
}
func (m *Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reservation.Unmarshal(m, b)
}
func (m *Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reservation.Marshal(b, m, deterministic)
}
func (m *Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reservation.Merge(m, src)
}
func (m *Reservation) XXX_Size() int {
	return xxx_messageInfo_Reservation.Size(m)
}
func (m *Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_Reservation proto.InternalMessageInfo

func (m *Reservation) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

func (m *Reservation) GetSeatCount() int64 {
	if m != nil {
		return m.SeatCount
	}
	return 0
}

func (m *Reservation) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Reservation) GetReservationName() string {
	if m != nil {
		return m.ReservationName
	}
	return ""
}

func (m *Reservation) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Reservation) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Reservation) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *Reservation) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Reservation) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

type BookReservationRequest struct {
	CustomerId           int64        `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Reservation          *Reservation `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BookReservationRequest) Reset()         { *m = BookReservationRequest{} }
func (m *BookReservationRequest) String() string { return proto.CompactTextString(m) }
func (*BookReservationRequest) ProtoMessage()    {}
func (*BookReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{1}
}
func (m *BookReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookReservationRequest.Unmarshal(m, b)
}
func (m *BookReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookReservationRequest.Marshal(b, m, deterministic)
}
func (m *BookReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookReservationRequest.Merge(m, src)
}
func (m *BookReservationRequest) XXX_Size() int {
	return xxx_messageInfo_BookReservationRequest.Size(m)
}
func (m *BookReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookReservationRequest proto.InternalMessageInfo

func (m *BookReservationRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *BookReservationRequest) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type BookReservationResponse struct {
	Reservation          *Reservation `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Err                  string       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BookReservationResponse) Reset()         { *m = BookReservationResponse{} }
func (m *BookReservationResponse) String() string { return proto.CompactTextString(m) }
func (*BookReservationResponse) ProtoMessage()    {}
func (*BookReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{2}
}
func (m *BookReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookReservationResponse.Unmarshal(m, b)
}
func (m *BookReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookReservationResponse.Marshal(b, m, deterministic)
}
func (m *BookReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookReservationResponse.Merge(m, src)
}
func (m *BookReservationResponse) XXX_Size() int {
	return xxx_messageInfo_BookReservationResponse.Size(m)
}
func (m *BookReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookReservationResponse proto.InternalMessageInfo

func (m *BookReservationResponse) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

func (m *BookReservationResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DiscardReservationRequest struct {
	ReservationId        int64    `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardReservationRequest) Reset()         { *m = DiscardReservationRequest{} }
func (m *DiscardReservationRequest) String() string { return proto.CompactTextString(m) }
func (*DiscardReservationRequest) ProtoMessage()    {}
func (*DiscardReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{3}
}
func (m *DiscardReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardReservationRequest.Unmarshal(m, b)
}
func (m *DiscardReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardReservationRequest.Marshal(b, m, deterministic)
}
func (m *DiscardReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardReservationRequest.Merge(m, src)
}
func (m *DiscardReservationRequest) XXX_Size() int {
	return xxx_messageInfo_DiscardReservationRequest.Size(m)
}
func (m *DiscardReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardReservationRequest proto.InternalMessageInfo

func (m *DiscardReservationRequest) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

type DiscardReservationResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardReservationResponse) Reset()         { *m = DiscardReservationResponse{} }
func (m *DiscardReservationResponse) String() string { return proto.CompactTextString(m) }
func (*DiscardReservationResponse) ProtoMessage()    {}
func (*DiscardReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{4}
}
func (m *DiscardReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardReservationResponse.Unmarshal(m, b)
}
func (m *DiscardReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardReservationResponse.Marshal(b, m, deterministic)
}
func (m *DiscardReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardReservationResponse.Merge(m, src)
}
func (m *DiscardReservationResponse) XXX_Size() int {
	return xxx_messageInfo_DiscardReservationResponse.Size(m)
}
func (m *DiscardReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardReservationResponse proto.InternalMessageInfo

func (m *DiscardReservationResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type EditReservationRequest struct {
	ReservationId        int64        `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Reservation          *Reservation `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EditReservationRequest) Reset()         { *m = EditReservationRequest{} }
func (m *EditReservationRequest) String() string { return proto.CompactTextString(m) }
func (*EditReservationRequest) ProtoMessage()    {}
func (*EditReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{5}
}
func (m *EditReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditReservationRequest.Unmarshal(m, b)
}
func (m *EditReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditReservationRequest.Marshal(b, m, deterministic)
}
func (m *EditReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditReservationRequest.Merge(m, src)
}
func (m *EditReservationRequest) XXX_Size() int {
	return xxx_messageInfo_EditReservationRequest.Size(m)
}
func (m *EditReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditReservationRequest proto.InternalMessageInfo

func (m *EditReservationRequest) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

func (m *EditReservationRequest) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type EditReservationResponse struct {
	Reservation          *Reservation `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Err                  string       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EditReservationResponse) Reset()         { *m = EditReservationResponse{} }
func (m *EditReservationResponse) String() string { return proto.CompactTextString(m) }
func (*EditReservationResponse) ProtoMessage()    {}
func (*EditReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{6}
}
func (m *EditReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditReservationResponse.Unmarshal(m, b)
}
func (m *EditReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditReservationResponse.Marshal(b, m, deterministic)
}
func (m *EditReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditReservationResponse.Merge(m, src)
}
func (m *EditReservationResponse) XXX_Size() int {
	return xxx_messageInfo_EditReservationResponse.Size(m)
}
func (m *EditReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditReservationResponse proto.InternalMessageInfo

func (m *EditReservationResponse) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

func (m *EditReservationResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetReservationHistoryPerCustomerRequest struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReservationHistoryPerCustomerRequest) Reset() {
	*m = GetReservationHistoryPerCustomerRequest{}
}
func (m *GetReservationHistoryPerCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetReservationHistoryPerCustomerRequest) ProtoMessage()    {}
func (*GetReservationHistoryPerCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{7}
}
func (m *GetReservationHistoryPerCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationHistoryPerCustomerRequest.Unmarshal(m, b)
}
func (m *GetReservationHistoryPerCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationHistoryPerCustomerRequest.Marshal(b, m, deterministic)
}
func (m *GetReservationHistoryPerCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationHistoryPerCustomerRequest.Merge(m, src)
}
func (m *GetReservationHistoryPerCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetReservationHistoryPerCustomerRequest.Size(m)
}
func (m *GetReservationHistoryPerCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationHistoryPerCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationHistoryPerCustomerRequest proto.InternalMessageInfo

func (m *GetReservationHistoryPerCustomerRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *GetReservationHistoryPerCustomerRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetReservationHistoryPerCustomerRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetReservationHistoryPerCustomerResponse struct {
	Reservations         []*Reservation `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	Err                  string         `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetReservationHistoryPerCustomerResponse) Reset() {
	*m = GetReservationHistoryPerCustomerResponse{}
}
func (m *GetReservationHistoryPerCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*GetReservationHistoryPerCustomerResponse) ProtoMessage()    {}
func (*GetReservationHistoryPerCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{8}
}
func (m *GetReservationHistoryPerCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationHistoryPerCustomerResponse.Unmarshal(m, b)
}
func (m *GetReservationHistoryPerCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationHistoryPerCustomerResponse.Marshal(b, m, deterministic)
}
func (m *GetReservationHistoryPerCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationHistoryPerCustomerResponse.Merge(m, src)
}
func (m *GetReservationHistoryPerCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_GetReservationHistoryPerCustomerResponse.Size(m)
}
func (m *GetReservationHistoryPerCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationHistoryPerCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationHistoryPerCustomerResponse proto.InternalMessageInfo

func (m *GetReservationHistoryPerCustomerResponse) GetReservations() []*Reservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

func (m *GetReservationHistoryPerCustomerResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Reservation)(nil), "Reservation")
	proto.RegisterType((*BookReservationRequest)(nil), "BookReservationRequest")
	proto.RegisterType((*BookReservationResponse)(nil), "BookReservationResponse")
	proto.RegisterType((*DiscardReservationRequest)(nil), "DiscardReservationRequest")
	proto.RegisterType((*DiscardReservationResponse)(nil), "DiscardReservationResponse")
	proto.RegisterType((*EditReservationRequest)(nil), "EditReservationRequest")
	proto.RegisterType((*EditReservationResponse)(nil), "EditReservationResponse")
	proto.RegisterType((*GetReservationHistoryPerCustomerRequest)(nil), "GetReservationHistoryPerCustomerRequest")
	proto.RegisterType((*GetReservationHistoryPerCustomerResponse)(nil), "GetReservationHistoryPerCustomerResponse")
}

func init() { proto.RegisterFile("reservation.proto", fileDescriptor_c1b272c5347b2042) }

var fileDescriptor_c1b272c5347b2042 = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x96, 0x93, 0xa6, 0x69, 0x26, 0x3d, 0xa7, 0x3d, 0xab, 0xaa, 0xf5, 0xf1, 0x69, 0xd5, 0x3d,
	0xe6, 0x2f, 0xad, 0xa8, 0x83, 0xca, 0x5d, 0x25, 0x2e, 0xd2, 0x82, 0xa0, 0x12, 0x02, 0x14, 0xe0,
	0x06, 0x2e, 0x22, 0x37, 0x9e, 0x86, 0x15, 0xf5, 0x6e, 0xba, 0xbb, 0xe9, 0x8f, 0xaa, 0x4a, 0x08,
	0x89, 0x17, 0x08, 0xcf, 0x81, 0xb8, 0x01, 0xf1, 0x06, 0xbc, 0x00, 0xaf, 0xc0, 0x83, 0xa0, 0x6c,
	0x1c, 0xba, 0x89, 0x13, 0x12, 0x15, 0xae, 0x9c, 0x99, 0xf9, 0x3c, 0xdf, 0xcc, 0xf8, 0xfb, 0x14,
	0xf8, 0x47, 0xa2, 0x42, 0x79, 0x14, 0x6a, 0x26, 0x78, 0xd0, 0x94, 0x42, 0x0b, 0x6f, 0xb9, 0x21,
	0x44, 0xe3, 0x00, 0xcb, 0x61, 0x93, 0x95, 0x43, 0xce, 0x85, 0x36, 0x45, 0x95, 0x54, 0x6f, 0x9a,
	0x47, 0x7d, 0xa3, 0x81, 0x7c, 0x43, 0x1d, 0x87, 0x8d, 0x06, 0xca, 0xb2, 0x68, 0x1a, 0x44, 0x1a,
	0xed, 0x7f, 0xc8, 0x40, 0xb1, 0x7a, 0xc1, 0x40, 0xae, 0xc1, 0xdf, 0x16, 0x61, 0x8d, 0x45, 0xae,
	0x43, 0x9d, 0x52, 0xb6, 0xfa, 0x97, 0x95, 0xdd, 0x8d, 0xc8, 0x0a, 0x80, 0xc2, 0x50, 0xd7, 0xea,
	0xa2, 0xc5, 0xb5, 0x9b, 0x31, 0x90, 0x42, 0x27, 0xb3, 0xd3, 0x49, 0x98, 0xb2, 0x0e, 0xa5, 0xae,
	0x69, 0x16, 0xa3, 0x9b, 0xa5, 0x4e, 0xa9, 0x50, 0x2d, 0x98, 0xcc, 0x33, 0x16, 0x23, 0x59, 0x83,
	0x79, 0x9b, 0x84, 0x87, 0x31, 0xba, 0x53, 0x06, 0x34, 0x67, 0xe5, 0x1f, 0x85, 0x31, 0x92, 0x55,
	0x28, 0xd6, 0x5b, 0x4a, 0x8b, 0x18, 0x65, 0x67, 0x98, 0x9c, 0x61, 0x82, 0x5e, 0x6a, 0x37, 0x22,
	0x0b, 0x90, 0x6b, 0xbe, 0x12, 0x1c, 0xdd, 0x69, 0xd3, 0xa0, 0x1b, 0x10, 0x0f, 0x66, 0xea, 0x22,
	0x8e, 0x91, 0x6b, 0xe5, 0xe6, 0x4d, 0xe1, 0x67, 0x4c, 0x5c, 0xc8, 0xd7, 0x25, 0x86, 0x1a, 0x23,
	0x77, 0xc6, 0xb4, 0xeb, 0x85, 0xe4, 0x7f, 0x98, 0x3d, 0x08, 0x95, 0xae, 0xb5, 0x9a, 0x91, 0x29,
	0x17, 0x4c, 0xb9, 0xd8, 0xc9, 0x3d, 0xef, 0xa6, 0x7c, 0x06, 0x8b, 0xdb, 0x42, 0xbc, 0xb6, 0x4e,
	0x56, 0xc5, 0xc3, 0x16, 0x2a, 0x3d, 0x38, 0xa9, 0x93, 0x9a, 0x34, 0x80, 0xa2, 0xb5, 0x9d, 0x39,
	0x5a, 0x71, 0x73, 0x36, 0xb0, 0x5b, 0xd9, 0x00, 0xff, 0x25, 0x2c, 0xa5, 0xa8, 0x54, 0x53, 0x70,
	0x85, 0x83, 0xad, 0x9c, 0x31, 0xad, 0xc8, 0x3c, 0x64, 0x51, 0x4a, 0x43, 0x59, 0xa8, 0x76, 0x7e,
	0xfa, 0xdb, 0xf0, 0xef, 0x5d, 0xa6, 0xea, 0xa1, 0x8c, 0x86, 0xac, 0x32, 0x99, 0x08, 0xfc, 0x00,
	0xbc, 0x61, 0x3d, 0x92, 0x19, 0x13, 0x4e, 0xe7, 0x82, 0x53, 0xc0, 0xe2, 0xbd, 0x88, 0xe9, 0x4b,
	0x13, 0x5e, 0xe6, 0x82, 0x29, 0xc2, 0x3f, 0x76, 0xc1, 0x13, 0xb8, 0x71, 0x1f, 0xed, 0xde, 0x0f,
	0x98, 0xd2, 0x42, 0x9e, 0x3e, 0x41, 0xb9, 0x93, 0x7c, 0xf4, 0x89, 0xa5, 0xb1, 0x00, 0xb9, 0x03,
	0x16, 0xb3, 0xae, 0x93, 0xa6, 0xaa, 0xdd, 0x80, 0x2c, 0xc2, 0xb4, 0xd8, 0xdf, 0x57, 0xa8, 0x8d,
	0x83, 0xa6, 0xaa, 0x49, 0xe4, 0x73, 0x28, 0x8d, 0x67, 0x4e, 0xf6, 0xbc, 0x05, 0xb3, 0xd6, 0x1a,
	0xca, 0x75, 0x68, 0x36, 0xb5, 0x68, 0x1f, 0x22, 0xbd, 0xe9, 0xe6, 0x9b, 0x3c, 0x10, 0x0b, 0xff,
	0x14, 0xe5, 0x11, 0xab, 0x23, 0xf9, 0xe4, 0xc0, 0xdc, 0x80, 0x40, 0xc9, 0x52, 0x30, 0xdc, 0x1d,
	0x9e, 0x1b, 0x8c, 0xd0, 0xb2, 0xcf, 0xdb, 0x95, 0x3b, 0x7d, 0x1f, 0x83, 0x18, 0x87, 0xd1, 0x90,
	0x72, 0x3c, 0xa6, 0xd6, 0x1b, 0xde, 0x88, 0xfc, 0xdb, 0x6f, 0xdf, 0xdf, 0x67, 0x4a, 0xfe, 0x95,
	0x72, 0xef, 0xa0, 0xe5, 0x33, 0xeb, 0xda, 0xe7, 0x65, 0xab, 0xf5, 0x96, 0xb3, 0x4e, 0xbe, 0x3a,
	0x40, 0xd2, 0xb2, 0x25, 0x5e, 0x30, 0xd2, 0x0f, 0xde, 0x7f, 0xc1, 0x68, 0x9d, 0xfb, 0xc7, 0xed,
	0xca, 0xe3, 0xfe, 0xf9, 0x57, 0x13, 0x34, 0x0d, 0x39, 0xc5, 0x13, 0xa6, 0x34, 0xe3, 0x0d, 0x6a,
	0x01, 0xbc, 0x71, 0x00, 0xb3, 0xd1, 0xea, 0xfa, 0x8a, 0x3d, 0x7a, 0xf9, 0xac, 0xdf, 0x21, 0xe7,
	0xe4, 0x8b, 0x03, 0x73, 0x03, 0xf2, 0x26, 0x4b, 0xc1, 0x70, 0x87, 0x79, 0x6e, 0x30, 0xc2, 0x09,
	0xfe, 0x61, 0xbb, 0xb2, 0xdb, 0x3f, 0xff, 0x72, 0x07, 0x3a, 0x72, 0xf8, 0x5f, 0x56, 0xbb, 0x93,
	0x7b, 0x63, 0x26, 0xff, 0x98, 0x01, 0x3a, 0x4e, 0xc1, 0xa4, 0x14, 0x4c, 0x68, 0x2f, 0x6f, 0x2d,
	0x98, 0xd4, 0x0e, 0xfe, 0x67, 0xa7, 0x5d, 0x79, 0xe7, 0xf4, 0xaf, 0xbb, 0xf5, 0x90, 0x29, 0x3d,
	0x74, 0x1b, 0x45, 0x9b, 0x28, 0x69, 0x4f, 0x4c, 0x54, 0xc8, 0x08, 0x25, 0x46, 0x74, 0xef, 0xb4,
	0x23, 0x41, 0x54, 0x3a, 0xf0, 0x7e, 0xe3, 0x5d, 0x73, 0xaa, 0xeb, 0xe4, 0xea, 0x04, 0xb2, 0x55,
	0xdb, 0xf9, 0x17, 0x39, 0xf3, 0x7f, 0xbd, 0x37, 0x6d, 0x1e, 0xb7, 0x7f, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xe3, 0x60, 0xea, 0x72, 0x17, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReservationServiceClient is the client API for ReservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReservationServiceClient interface {
	BookReservation(ctx context.Context, in *BookReservationRequest, opts ...grpc.CallOption) (*BookReservationResponse, error)
	DiscardReservation(ctx context.Context, in *DiscardReservationRequest, opts ...grpc.CallOption) (*DiscardReservationResponse, error)
	EditReservation(ctx context.Context, in *EditReservationRequest, opts ...grpc.CallOption) (*EditReservationResponse, error)
	GetReservationHistoryPerCustomer(ctx context.Context, in *GetReservationHistoryPerCustomerRequest, opts ...grpc.CallOption) (*GetReservationHistoryPerCustomerResponse, error)
}

type reservationServiceClient struct {
	cc *grpc.ClientConn
}

func NewReservationServiceClient(cc *grpc.ClientConn) ReservationServiceClient {
	return &reservationServiceClient{cc}
}

func (c *reservationServiceClient) BookReservation(ctx context.Context, in *BookReservationRequest, opts ...grpc.CallOption) (*BookReservationResponse, error) {
	out := new(BookReservationResponse)
	err := c.cc.Invoke(ctx, "/ReservationService/BookReservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) DiscardReservation(ctx context.Context, in *DiscardReservationRequest, opts ...grpc.CallOption) (*DiscardReservationResponse, error) {
	out := new(DiscardReservationResponse)
	err := c.cc.Invoke(ctx, "/ReservationService/DiscardReservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) EditReservation(ctx context.Context, in *EditReservationRequest, opts ...grpc.CallOption) (*EditReservationResponse, error) {
	out := new(EditReservationResponse)
	err := c.cc.Invoke(ctx, "/ReservationService/EditReservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) GetReservationHistoryPerCustomer(ctx context.Context, in *GetReservationHistoryPerCustomerRequest, opts ...grpc.CallOption) (*GetReservationHistoryPerCustomerResponse, error) {
	out := new(GetReservationHistoryPerCustomerResponse)
	err := c.cc.Invoke(ctx, "/ReservationService/GetReservationHistoryPerCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReservationServiceServer is the server API for ReservationService service.
type ReservationServiceServer interface {
	BookReservation(context.Context, *BookReservationRequest) (*BookReservationResponse, error)
	DiscardReservation(context.Context, *DiscardReservationRequest) (*DiscardReservationResponse, error)
	EditReservation(context.Context, *EditReservationRequest) (*EditReservationResponse, error)
	GetReservationHistoryPerCustomer(context.Context, *GetReservationHistoryPerCustomerRequest) (*GetReservationHistoryPerCustomerResponse, error)
}

// UnimplementedReservationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReservationServiceServer struct {
}

func (*UnimplementedReservationServiceServer) BookReservation(ctx context.Context, req *BookReservationRequest) (*BookReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookReservation not implemented")
}
func (*UnimplementedReservationServiceServer) DiscardReservation(ctx context.Context, req *DiscardReservationRequest) (*DiscardReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscardReservation not implemented")
}
func (*UnimplementedReservationServiceServer) EditReservation(ctx context.Context, req *EditReservationRequest) (*EditReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditReservation not implemented")
}
func (*UnimplementedReservationServiceServer) GetReservationHistoryPerCustomer(ctx context.Context, req *GetReservationHistoryPerCustomerRequest) (*GetReservationHistoryPerCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReservationHistoryPerCustomer not implemented")
}

func RegisterReservationServiceServer(s *grpc.Server, srv ReservationServiceServer) {
	s.RegisterService(&_ReservationService_serviceDesc, srv)
}

func _ReservationService_BookReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).BookReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReservationService/BookReservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).BookReservation(ctx, req.(*BookReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_DiscardReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).DiscardReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReservationService/DiscardReservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).DiscardReservation(ctx, req.(*DiscardReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_EditReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).EditReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReservationService/EditReservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).EditReservation(ctx, req.(*EditReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_GetReservationHistoryPerCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReservationHistoryPerCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).GetReservationHistoryPerCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReservationService/GetReservationHistoryPerCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).GetReservationHistoryPerCustomer(ctx, req.(*GetReservationHistoryPerCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReservationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ReservationService",
	HandlerType: (*ReservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookReservation",
			Handler:    _ReservationService_BookReservation_Handler,
		},
		{
			MethodName: "DiscardReservation",
			Handler:    _ReservationService_DiscardReservation_Handler,
		},
		{
			MethodName: "EditReservation",
			Handler:    _ReservationService_EditReservation_Handler,
		},
		{
			MethodName: "GetReservationHistoryPerCustomer",
			Handler:    _ReservationService_GetReservationHistoryPerCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reservation.proto",
}
