// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-08-14 18:05:36.613005 +0300 EEST m=+0.065788785

package docs

import (
	"bytes"
	"encoding/json"
	"github.com/swaggo/swag"
	"html/template"
	"io/ioutil"
)

var doc = readSwaggerJSON()

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}

func readSwaggerJSON() string {
	b, err := ioutil.ReadFile("swagger.json")
	if err != nil {
		panic(err)
	}

	return string(b)
}
